// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParkSpotTLV.Infrastructure;

#nullable disable

namespace ParkSpotTLV.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.DevicePushToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("platform");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device_push_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("UX_DevicePushToken_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_DevicePushToken_UserId");

                    b.ToTable("device_push_tokens", (string)null);
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.ParkingDailyBudget", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<DateOnly>("AnchorDate")
                        .HasColumnType("date")
                        .HasColumnName("anchor_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MinutesUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("minutes_used");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("VehicleId", "AnchorDate")
                        .HasName("pk_daily_budgets");

                    b.ToTable("daily_budgets", (string)null);
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.ParkingNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sent");

                    b.Property<string>("JobId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("job_id");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<int>("NotificationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("notification_minutes");

                    b.Property<DateTimeOffset>("NotifyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notify_at");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_message_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<Guid?>("TokenIdSnapshot")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_parking_notifications");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_parking_notifications_session_id");

                    b.HasIndex("NotifyAt", "IsSent")
                        .HasDatabaseName("ix_parking_notifications_notify_at_is_sent");

                    b.HasIndex("NotifyAt", "Status")
                        .HasDatabaseName("IX_notification_notify_at_status");

                    b.ToTable("parking_notifications", (string)null);
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.ParkingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("group");

                    b.Property<bool>("IsPayLater")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pay_later");

                    b.Property<bool>("IsPayNow")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pay_now");

                    b.Property<DateTimeOffset?>("NextChange")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_change");

                    b.Property<int?>("NotificationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("notification_minutes");

                    b.Property<int>("PaidMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("paid_minutes");

                    b.Property<int>("ParkingBudgetUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("parking_budget_used");

                    b.Property<int>("ParkingType")
                        .HasColumnType("integer")
                        .HasColumnName("parking_type");

                    b.Property<DateTimeOffset?>("PlannedEndLocal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_end_local");

                    b.Property<string>("Reason")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("segment_id");

                    b.Property<DateTimeOffset?>("StartedLocal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_local");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StoppedLocal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stopped_local");

                    b.Property<int>("Tariff")
                        .HasColumnType("integer")
                        .HasColumnName("tariff");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<int?>("ZoneCode")
                        .HasColumnType("integer")
                        .HasColumnName("zone_code");

                    b.HasKey("Id")
                        .HasName("pk_parking_sessions");

                    b.HasIndex("StartedLocal")
                        .HasDatabaseName("ix_parking_sessions_started_local");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("IX_parking_sessions_vehicle_active")
                        .HasFilter("\"stopped_local\" IS NULL");

                    b.HasIndex("VehicleId", "Status")
                        .HasDatabaseName("ix_parking_sessions_vehicle_id_status");

                    b.ToTable("parking_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_parking_sessions_paid_minutes", "\"paid_minutes\" >= 0");

                            t.HasCheckConstraint("ck_parking_sessions_parking_budget_used", "\"parking_budget_used\" >= 0");
                        });
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.Permit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int?>("ZoneCode")
                        .HasColumnType("integer")
                        .HasColumnName("zone_code");

                    b.HasKey("Id")
                        .HasName("pk_permits");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_permits_vehicle_id");

                    b.HasIndex("ZoneCode")
                        .HasDatabaseName("ix_permits_zone_code");

                    b.ToTable("permits", (string)null);
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("ReplacedByTokenHash")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_token_hash");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("ix_refresh_tokens_revoked_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.StreetSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<LineString>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(LineString,4326)")
                        .HasColumnName("geom");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_english");

                    b.Property<string>("NameHebrew")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_hebrew");

                    b.Property<string>("OSMId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("osm_id");

                    b.Property<int>("ParkingType")
                        .HasColumnType("integer")
                        .HasColumnName("parking_type");

                    b.Property<int>("Side")
                        .HasColumnType("integer")
                        .HasColumnName("side");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_street_segments");

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_street_segments_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "GIST");

                    b.HasIndex("OSMId")
                        .HasDatabaseName("ix_street_segments_osm_id");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_street_segments_zone_id");

                    b.ToTable("street_segments", (string)null);
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.TariffWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndLocal")
                        .HasColumnType("time")
                        .HasColumnName("end_local");

                    b.Property<TimeOnly>("StartLocal")
                        .HasColumnType("time")
                        .HasColumnName("start_local");

                    b.Property<int>("Tariff")
                        .HasColumnType("integer")
                        .HasColumnName("tariff");

                    b.HasKey("Id")
                        .HasName("pk_tariff_windows");

                    b.HasIndex("Tariff", "DayOfWeek")
                        .HasDatabaseName("ix_tariff_windows_tariff_day_of_week");

                    b.ToTable("tariff_windows", (string)null);
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_vehicles_owner_id");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_owner_id_name");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<MultiPolygon>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geom");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("name");

                    b.Property<int>("Taarif")
                        .HasColumnType("integer")
                        .HasColumnName("taarif");

                    b.HasKey("Id")
                        .HasName("pk_zones");

                    b.HasAlternateKey("Code")
                        .HasName("ak_zones_code");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_zones_code");

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_zones_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "GIST");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.ParkingDailyBudget", b =>
                {
                    b.HasOne("ParkSpotTLV.Infrastructure.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_budgets_vehicles_vehicle_id");
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.ParkingNotification", b =>
                {
                    b.HasOne("ParkSpotTLV.Infrastructure.Entities.ParkingSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parking_notifications_parking_session_session_id");
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.Permit", b =>
                {
                    b.HasOne("ParkSpotTLV.Infrastructure.Entities.Vehicle", "Vehicle")
                        .WithMany("Permits")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permits_vehicles_vehicle_id");

                    b.HasOne("ParkSpotTLV.Infrastructure.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_permits_zones_zone_code");

                    b.Navigation("Vehicle");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.RefreshToken", b =>
                {
                    b.HasOne("ParkSpotTLV.Infrastructure.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.StreetSegment", b =>
                {
                    b.HasOne("ParkSpotTLV.Infrastructure.Entities.Zone", "Zone")
                        .WithMany("Segments")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_street_segments_zones_zone_id");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.Vehicle", b =>
                {
                    b.HasOne("ParkSpotTLV.Infrastructure.Entities.User", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.Vehicle", b =>
                {
                    b.Navigation("Permits");
                });

            modelBuilder.Entity("ParkSpotTLV.Infrastructure.Entities.Zone", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
